name: realheros_durga
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  thumbnails:
    git:
      url: https://github.com/divyanshub024/Flutter_Thumbnails.git
  esys_flutter_share:
    git:
      url: https://github.com/dudhatparesh/esys-flutter-share.git
  animated_splash: ^1.0.0
  animated_text_kit: ^4.2.1
  audioplayer: ^0.8.1
  beacon_monitoring: ^2.0.0
  camera: ^0.8.1+3
  carousel_pro: ^1.0.0
  cloud_firestore: ^2.2.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  firebase_analytics: ^8.1.1
  firebase_auth: ^1.3.0
  firebase_core: ^1.2.1
  firebase_database: ^7.1.0
  firebase_messaging: ^10.0.1
  flutter_local_notifications: ^6.0.0
  flutter_phone_direct_caller: ^2.0.0
  flutter_polyline_points: ^1.0.0
  flutter_signin_button: ^2.0.0
  flutter_geofire: ^2.0.0
  font_awesome_flutter: ^9.1.0
  form_field_validator: ^1.1.0
  geoflutterfire: ^3.0.0-nullsafety.4
  google_maps_flutter: ^2.0.6
  geolocator: ^7.2.0+1
  google_nav_bar: ^5.0.5
  http: ^0.13.3
  image_gallery_saver: ^1.6.9
  image_picker: 0.7.4
  intl: ^0.17.0
  location: ^4.3.0
  maps_toolkit: ^2.0.0
  overlay_support: ^1.2.1
  path: ^1.8.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  rxdart: ^0.27.1
  slider_button: ^1.0.0
  slider_side_menu: ^0.1.0
  stream_chat_flutter: ^2.0.0-nullsafety.4
  switcher_button: ^0.0.3
  toast: ^0.1.5
  url_launcher: ^6.0.6
  video_player: ^2.1.5
  video_thumbnail: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  get_it: ^7.1.3
  local_auth: ^1.1.6

flutter_icons:
  image_path: “assets/durga-india.png”
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/drawer_image.png
    - assets/logo.png
    - assets/drawerlogo1.png
    - assets/durga-india.jpg
    - assets/durga-india.png
    - assets/videoplayback.mp4
    - assets/facebook.png
    - assets/Indian Police siren.mp3
    - assets/Siren.mp3
    - assets/Police Siren.mp3
    - assets/Google_logo.png
    - assets/Photo1.jpg
    - assets/1.jpeg
    - assets/2.jpeg
    - assets/3.jpeg
    - assets/4.jpeg
    - assets/vaishnavi.jpg
    - assets/BluTree Drawer.jpeg
    - assets/Blutree-Durga.jpeg
    - assets/Blutree-Durga1.jpeg
    - assets/Blutree Logo.jpeg
    - assets/Blutree Logo(1).jpeg
    - assets/Drawer(Red Logo1).jpg
    - assets/durgadrawer.jpg
    - assets/user_icon.png
    - assets/alert.mp3
    - assets/Picture1.png
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/OpenSans.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
